spring.application.name=teacher-student-backend

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/teacher_student_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
# 1. Instruct Hibernate to create tables ONLY if they do not exist
spring.jpa.hibernate.ddl-auto=update

# 2. Force data scripts to run AFTER validation/startup processes finish
spring.jpa.defer-datasource-initialization=true

# 3. Ensure script processing is fully enabled
spring.sql.init.mode=always
